services:
  app:
    image: frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Add this line to ensure the node_modules is handled inside the container.
    ports:
      - 5173:5173
    container_name: front
